- name: Test ansible playbook for awx
  gather_facts: false
  become: true
  become_method: sudo
  hosts: all
  tasks:

    - name: Get uptime
      command: uptime
      register: res
    - debug: msg="{{ res.stdout }}"
    
    - name: Get dmesg
      command: dmesg
      register: res
    - debug: msg="{{ res.stdout }}"
    - name: Get id
      command: id
      register: res
    - debug: msg="{{ res.stdout }}"
