- name: Test ansible playbook for awx
  gather_facts: false
  hosts: all
  tasks:

    - name: Get uptime
      command: uptime
      register: res
    - debug: msg="{{ res.stdout }}"
    
    - name: Get dmesg
      command: dmesg
      register: res
    - debug: msg="{{ res.stdout }}"
